// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_offers.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactOfferByRequestAndOfferer = `-- name: GetContactOfferByRequestAndOfferer :one
SELECT id, request_id, offerer_phone, offerer_name, created_at
FROM contact_offers WHERE request_id = $1 AND offerer_phone = $2
`

type GetContactOfferByRequestAndOffererParams struct {
	RequestID    pgtype.UUID `db:"request_id"`
	OffererPhone string      `db:"offerer_phone"`
}

func (q *Queries) GetContactOfferByRequestAndOfferer(ctx context.Context, arg GetContactOfferByRequestAndOffererParams) (ContactOffer, error) {
	row := q.db.QueryRow(ctx, getContactOfferByRequestAndOfferer, arg.RequestID, arg.OffererPhone)
	var i ContactOffer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OffererPhone,
		&i.OffererName,
		&i.CreatedAt,
	)
	return i, err
}

const insertContactOffer = `-- name: InsertContactOffer :exec
INSERT INTO contact_offers (id, request_id, offerer_phone, offerer_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (request_id, offerer_phone) DO NOTHING
`

type InsertContactOfferParams struct {
	ID           pgtype.UUID `db:"id"`
	RequestID    pgtype.UUID `db:"request_id"`
	OffererPhone string      `db:"offerer_phone"`
	OffererName  string      `db:"offerer_name"`
}

func (q *Queries) InsertContactOffer(ctx context.Context, arg InsertContactOfferParams) error {
	_, err := q.db.Exec(ctx, insertContactOffer,
		arg.ID,
		arg.RequestID,
		arg.OffererPhone,
		arg.OffererName,
	)
	return err
}

const listContactOffersByRequest = `-- name: ListContactOffersByRequest :many
SELECT id, request_id, offerer_phone, offerer_name, created_at
FROM contact_offers WHERE request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListContactOffersByRequest(ctx context.Context, requestID pgtype.UUID) ([]ContactOffer, error) {
	rows, err := q.db.Query(ctx, listContactOffersByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactOffer{}
	for rows.Next() {
		var i ContactOffer
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.OffererPhone,
			&i.OffererName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
