// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package queries

import (
	"context"
)

const listDestinations = `-- name: ListDestinations :many
SELECT MIN(location)::text AS location FROM (
  SELECT origin      AS location FROM rides
  UNION ALL SELECT destination   FROM rides
  UNION ALL SELECT origin        FROM requests
  UNION ALL SELECT destination   FROM requests
  UNION ALL SELECT origin        FROM ride_stats
  UNION ALL SELECT destination   FROM ride_stats
) all_locs
GROUP BY LOWER(location)
ORDER BY COUNT(*) DESC, MIN(location) ASC
`

// Returns known locations sorted by popularity. Combines active rides/requests
// with historical ride_stats so locations persist after rides expire.
func (q *Queries) ListDestinations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
