// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback_queue.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExhaustedFeedback = `-- name: DeleteExhaustedFeedback :exec
DELETE FROM feedback_queue
WHERE sent_count >= $1::int
   OR created_at < $2::timestamptz
`

type DeleteExhaustedFeedbackParams struct {
	MaxRetries int32              `db:"max_retries"`
	TtlBefore  pgtype.Timestamptz `db:"ttl_before"`
}

func (q *Queries) DeleteExhaustedFeedback(ctx context.Context, arg DeleteExhaustedFeedbackParams) error {
	_, err := q.db.Exec(ctx, deleteExhaustedFeedback, arg.MaxRetries, arg.TtlBefore)
	return err
}

const deleteFeedbackByRideID = `-- name: DeleteFeedbackByRideID :execrows
DELETE FROM feedback_queue WHERE ride_id = $1
`

// :execrows returns the number of rows deleted, used as the "claim" signal in
// RecordFeedback: only the caller that actually deletes the row records the stat.
func (q *Queries) DeleteFeedbackByRideID(ctx context.Context, rideID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeedbackByRideID, rideID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueStartedRides = `-- name: EnqueueStartedRides :exec
INSERT INTO feedback_queue (ride_id, phone, origin, destination, ride_date, departure_at, send_after)
SELECT r.id, r.phone, r.origin, r.destination, r.date, r.departure_at,
       r.departure_at + (r.flexibility * INTERVAL '1 minute') + INTERVAL '1 hour'
FROM rides r
WHERE r.departure_at <= NOW()
  AND r.departure_at > $1::timestamptz
  AND r.feedback_given = false
  AND NOT EXISTS (SELECT 1 FROM feedback_queue fq WHERE fq.ride_id = r.id)
ON CONFLICT (ride_id) DO NOTHING
`

// Inserts a feedback task for every ride whose window has started (departure in
// the past, but within the bound), that hasn't been answered, and isn't already
// queued. send_after = window end (departure + flexibility minutes) + 1 hour.
// Idempotent via ride_id UNIQUE.
func (q *Queries) EnqueueStartedRides(ctx context.Context, windowStartAfter pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, enqueueStartedRides, windowStartAfter)
	return err
}

const findDueFeedback = `-- name: FindDueFeedback :many
SELECT id, ride_id, phone, origin, destination, ride_date, departure_at, send_after, sent_count, last_sent_at, created_at
FROM feedback_queue
WHERE send_after <= NOW()
  AND sent_count < $1::int
  AND (last_sent_at IS NULL OR last_sent_at < $2::timestamptz)
ORDER BY send_after ASC
`

type FindDueFeedbackParams struct {
	MaxRetries  int32              `db:"max_retries"`
	RetryBefore pgtype.Timestamptz `db:"retry_before"`
}

// Tasks past their send time and still retry-eligible.
func (q *Queries) FindDueFeedback(ctx context.Context, arg FindDueFeedbackParams) ([]FeedbackQueue, error) {
	rows, err := q.db.Query(ctx, findDueFeedback, arg.MaxRetries, arg.RetryBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedbackQueue{}
	for rows.Next() {
		var i FeedbackQueue
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.RideDate,
			&i.DepartureAt,
			&i.SendAfter,
			&i.SentCount,
			&i.LastSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByRideID = `-- name: GetFeedbackByRideID :one
SELECT id, ride_id, phone, origin, destination, ride_date, departure_at, send_after, sent_count, last_sent_at, created_at
FROM feedback_queue
WHERE ride_id = $1
`

func (q *Queries) GetFeedbackByRideID(ctx context.Context, rideID pgtype.UUID) (FeedbackQueue, error) {
	row := q.db.QueryRow(ctx, getFeedbackByRideID, rideID)
	var i FeedbackQueue
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Phone,
		&i.Origin,
		&i.Destination,
		&i.RideDate,
		&i.DepartureAt,
		&i.SendAfter,
		&i.SentCount,
		&i.LastSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const markFeedbackSent = `-- name: MarkFeedbackSent :exec
UPDATE feedback_queue
SET sent_count = sent_count + 1,
    last_sent_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkFeedbackSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFeedbackSent, id)
	return err
}
