// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInterest = `-- name: AcceptInterest :exec
UPDATE interests SET status = 'accepted' WHERE id = $1
`

func (q *Queries) AcceptInterest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptInterest, id)
	return err
}

const getInterestByID = `-- name: GetInterestByID :one
SELECT id, ride_id, searcher_phone, searcher_name, status, created_at
FROM interests WHERE id = $1
`

func (q *Queries) GetInterestByID(ctx context.Context, id pgtype.UUID) (Interest, error) {
	row := q.db.QueryRow(ctx, getInterestByID, id)
	var i Interest
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.SearcherPhone,
		&i.SearcherName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInterestByRideAndSearcher = `-- name: GetInterestByRideAndSearcher :one
SELECT id, ride_id, searcher_phone, searcher_name, status, created_at
FROM interests WHERE ride_id = $1 AND searcher_phone = $2
`

type GetInterestByRideAndSearcherParams struct {
	RideID        pgtype.UUID `db:"ride_id"`
	SearcherPhone string      `db:"searcher_phone"`
}

func (q *Queries) GetInterestByRideAndSearcher(ctx context.Context, arg GetInterestByRideAndSearcherParams) (Interest, error) {
	row := q.db.QueryRow(ctx, getInterestByRideAndSearcher, arg.RideID, arg.SearcherPhone)
	var i Interest
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.SearcherPhone,
		&i.SearcherName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertInterest = `-- name: InsertInterest :exec
INSERT INTO interests (id, ride_id, searcher_phone, searcher_name, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (ride_id, searcher_phone) DO NOTHING
`

type InsertInterestParams struct {
	ID            pgtype.UUID `db:"id"`
	RideID        pgtype.UUID `db:"ride_id"`
	SearcherPhone string      `db:"searcher_phone"`
	SearcherName  string      `db:"searcher_name"`
	Status        string      `db:"status"`
}

func (q *Queries) InsertInterest(ctx context.Context, arg InsertInterestParams) error {
	_, err := q.db.Exec(ctx, insertInterest,
		arg.ID,
		arg.RideID,
		arg.SearcherPhone,
		arg.SearcherName,
		arg.Status,
	)
	return err
}

const listInterestsByRide = `-- name: ListInterestsByRide :many
SELECT id, ride_id, searcher_phone, searcher_name, status, created_at
FROM interests WHERE ride_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListInterestsByRide(ctx context.Context, rideID pgtype.UUID) ([]Interest, error) {
	rows, err := q.db.Query(ctx, listInterestsByRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Interest{}
	for rows.Next() {
		var i Interest
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.SearcherPhone,
			&i.SearcherName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
