// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Interest struct {
	ID            pgtype.UUID        `db:"id"`
	RideID        pgtype.UUID        `db:"ride_id"`
	SearcherPhone string             `db:"searcher_phone"`
	SearcherName  string             `db:"searcher_name"`
	Status        string             `db:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

type Request struct {
	ID           pgtype.UUID        `db:"id"`
	SearcherName string             `db:"searcher_name"`
	Phone        string             `db:"phone"`
	Origin       string             `db:"origin"`
	Destination  string             `db:"destination"`
	Date         pgtype.Date        `db:"date"`
	DepartureAt  pgtype.Timestamptz `db:"departure_at"`
	Flexibility  int32              `db:"flexibility"`
	PostedAt     pgtype.Timestamptz `db:"posted_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at"`
}

type Ride struct {
	ID            pgtype.UUID        `db:"id"`
	DriverName    string             `db:"driver_name"`
	Phone         string             `db:"phone"`
	Origin        string             `db:"origin"`
	Destination   string             `db:"destination"`
	Date          pgtype.Date        `db:"date"`
	DepartureAt   pgtype.Timestamptz `db:"departure_at"`
	Flexibility   int32              `db:"flexibility"`
	PostedAt      pgtype.Timestamptz `db:"posted_at"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at"`
	FeedbackGiven bool               `db:"feedback_given"`
}

type RideEvent struct {
	ID          pgtype.UUID        `db:"id"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	PostedAt    pgtype.Timestamptz `db:"posted_at"`
}

type RideStat struct {
	ID          pgtype.UUID        `db:"id"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	RideDate    pgtype.Date        `db:"ride_date"`
	Taken       bool               `db:"taken"`
	RecordedAt  pgtype.Timestamptz `db:"recorded_at"`
}

type SearchEvent struct {
	ID          pgtype.UUID        `db:"id"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	SearchedAt  pgtype.Timestamptz `db:"searched_at"`
}

type Subscription struct {
	ID       pgtype.UUID `db:"id"`
	Phone    string      `db:"phone"`
	Endpoint string      `db:"endpoint"`
	P256dh   string      `db:"p256dh"`
	Auth     string      `db:"auth"`
}
