// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInterest(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredRequests(ctx context.Context) error
	DeleteExpiredRides(ctx context.Context) error
	DeleteRequest(ctx context.Context, id pgtype.UUID) error
	DeleteRide(ctx context.Context, id pgtype.UUID) error
	DeleteSubscription(ctx context.Context, phone string) error
	// Matches all alert modes inferred from NULL state of date/departure_at:
	//   anytime: date IS NULL AND departure_at IS NULL
	//   daily:   date IS NULL AND departure_at IS NOT NULL (time-only match)
	//   day:     date set, departure_at IS NULL
	//   time:    both set (overlapping window)
	FindRequestsMatchingRide(ctx context.Context, arg FindRequestsMatchingRideParams) ([]Request, error)
	FindRidesMatchingAnytimeRequest(ctx context.Context, arg FindRidesMatchingAnytimeRequestParams) ([]Ride, error)
	FindRidesMatchingDailyRequest(ctx context.Context, arg FindRidesMatchingDailyRequestParams) ([]Ride, error)
	FindRidesMatchingDayRequest(ctx context.Context, arg FindRidesMatchingDayRequestParams) ([]Ride, error)
	FindRidesMatchingTimeRequest(ctx context.Context, arg FindRidesMatchingTimeRequestParams) ([]Ride, error)
	GetInterestByID(ctx context.Context, id pgtype.UUID) (Interest, error)
	GetInterestByRideAndSearcher(ctx context.Context, arg GetInterestByRideAndSearcherParams) (Interest, error)
	GetRequestByID(ctx context.Context, id pgtype.UUID) (Request, error)
	GetRideByID(ctx context.Context, id pgtype.UUID) (Ride, error)
	GetRideEventCounts(ctx context.Context) (GetRideEventCountsRow, error)
	GetRideStatsTotals(ctx context.Context) (GetRideStatsTotalsRow, error)
	GetSearchEventCounts(ctx context.Context) (GetSearchEventCountsRow, error)
	GetSubscriptionByPhone(ctx context.Context, phone string) (Subscription, error)
	GetTopRoutes(ctx context.Context) ([]GetTopRoutesRow, error)
	InsertInterest(ctx context.Context, arg InsertInterestParams) error
	InsertRequest(ctx context.Context, arg InsertRequestParams) error
	InsertRide(ctx context.Context, arg InsertRideParams) error
	InsertRideEvent(ctx context.Context, arg InsertRideEventParams) error
	InsertRideStat(ctx context.Context, arg InsertRideStatParams) error
	InsertSearchEvent(ctx context.Context, arg InsertSearchEventParams) error
	// Returns known locations sorted by popularity. Combines active rides/requests
	// with historical ride_stats so locations persist after rides expire.
	ListDestinations(ctx context.Context) ([]string, error)
	ListInterestsByRide(ctx context.Context, rideID pgtype.UUID) ([]Interest, error)
	ListRequestsByPhone(ctx context.Context, phone string) ([]Request, error)
	// grace_minutes: hides rides whose flex window ended more than N minutes ago
	ListRidesActive(ctx context.Context, graceMinutes int32) ([]Ride, error)
	ListRidesByPhone(ctx context.Context, phone string) ([]Ride, error)
	ListRidesPendingFeedback(ctx context.Context) ([]Ride, error)
	SearchRides(ctx context.Context, arg SearchRidesParams) ([]Ride, error)
	SearchRidesByDate(ctx context.Context, arg SearchRidesByDateParams) ([]Ride, error)
	// Returns rides on the given date whose departure window (±flexibility) overlaps
	// the search time ± search_tolerance_minutes. Hides expired/past-grace rides.
	SearchRidesByDateTime(ctx context.Context, arg SearchRidesByDateTimeParams) ([]Ride, error)
	// Time-only search: any date, departure window overlaps search_time ± tolerance.
	SearchRidesByTime(ctx context.Context, arg SearchRidesByTimeParams) ([]Ride, error)
	SetRideFeedbackGiven(ctx context.Context, id pgtype.UUID) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
