// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInterest(ctx context.Context, id pgtype.UUID) error
	// Returns interest counts for a set of ride IDs.
	CountInterestsByRides(ctx context.Context, dollar_1 []pgtype.UUID) ([]CountInterestsByRidesRow, error)
	DeleteExhaustedFeedback(ctx context.Context, arg DeleteExhaustedFeedbackParams) error
	DeleteExpiredNotifications(ctx context.Context) error
	DeleteExpiredRequests(ctx context.Context) error
	DeleteExpiredRides(ctx context.Context) error
	// :execrows returns the number of rows deleted, used as the "claim" signal in
	// RecordFeedback: only the caller that actually deletes the row records the stat.
	DeleteFeedbackByRideID(ctx context.Context, rideID pgtype.UUID) (int64, error)
	DeleteInterest(ctx context.Context, id pgtype.UUID) error
	DeleteNotificationsForRide(ctx context.Context, rideID pgtype.UUID) error
	DeleteRequest(ctx context.Context, id pgtype.UUID) error
	DeleteRide(ctx context.Context, id pgtype.UUID) error
	DeleteSubscription(ctx context.Context, phone string) error
	// Removes a specific device subscription (e.g. when push returns 410 Gone).
	DeleteSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error
	// Inserts a feedback task for every ride whose window has started (departure in
	// the past, but within the bound), that hasn't been answered, and isn't already
	// queued. send_after = window end (departure + flexibility minutes) + 1 hour.
	// Idempotent via ride_id UNIQUE.
	EnqueueStartedRides(ctx context.Context, windowStartAfter pgtype.Timestamptz) error
	// Tasks past their send time and still retry-eligible.
	FindDueFeedback(ctx context.Context, arg FindDueFeedbackParams) ([]FeedbackQueue, error)
	// Returns entries due for (re-)notification.
	// Excludes entries where the searcher has already expressed interest.
	FindPendingNotifications(ctx context.Context, arg FindPendingNotificationsParams) ([]NotificationQueue, error)
	// Matches all alert modes inferred from NULL state of date/departure_at:
	//   anytime: date IS NULL AND departure_at IS NULL
	//   daily:   date IS NULL AND departure_at IS NOT NULL (time-only match)
	//   day:     date set, departure_at IS NULL
	//   time:    both set (overlapping window)
	FindRequestsMatchingRide(ctx context.Context, arg FindRequestsMatchingRideParams) ([]Request, error)
	FindRidesMatchingAnytimeRequest(ctx context.Context, arg FindRidesMatchingAnytimeRequestParams) ([]Ride, error)
	FindRidesMatchingDailyRequest(ctx context.Context, arg FindRidesMatchingDailyRequestParams) ([]Ride, error)
	FindRidesMatchingDayRequest(ctx context.Context, arg FindRidesMatchingDayRequestParams) ([]Ride, error)
	FindRidesMatchingTimeRequest(ctx context.Context, arg FindRidesMatchingTimeRequestParams) ([]Ride, error)
	GetFeedbackByRideID(ctx context.Context, rideID pgtype.UUID) (FeedbackQueue, error)
	GetInterestByID(ctx context.Context, id pgtype.UUID) (Interest, error)
	GetInterestByRideAndSearcher(ctx context.Context, arg GetInterestByRideAndSearcherParams) (Interest, error)
	GetRequestByID(ctx context.Context, id pgtype.UUID) (Request, error)
	GetRideByID(ctx context.Context, id pgtype.UUID) (Ride, error)
	GetRideEventCounts(ctx context.Context) (GetRideEventCountsRow, error)
	GetRideStatsTotals(ctx context.Context) (GetRideStatsTotalsRow, error)
	GetSearchEventCounts(ctx context.Context) (GetSearchEventCountsRow, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTopRoutes(ctx context.Context) ([]GetTopRoutesRow, error)
	InsertInterest(ctx context.Context, arg InsertInterestParams) error
	InsertRequest(ctx context.Context, arg InsertRequestParams) error
	InsertRide(ctx context.Context, arg InsertRideParams) error
	InsertRideEvent(ctx context.Context, arg InsertRideEventParams) error
	InsertRideStat(ctx context.Context, arg InsertRideStatParams) error
	InsertSearchEvent(ctx context.Context, arg InsertSearchEventParams) error
	InsertSettingIfAbsent(ctx context.Context, arg InsertSettingIfAbsentParams) error
	// Public feed of all non-expired requests, ordered so concrete demand comes
	// first and the vaguest alerts sink to the bottom:
	//   0 dated (a one-off date+time, OR a date-only "any time that day")
	//   1 a daily recurring time   2 anytime
	// Within the dated group, sort chronologically by the effective moment — a
	// date-only alert sorts at the END of its day (a one-second-before-midnight
	// key), so it sits below same-day date+time entries yet above any later day.
	// A daily alert carries a 1970-01-01 sentinel departure_at, so any later year
	// marks a concrete one-off. Newest breaks ties.
	ListActiveRequests(ctx context.Context, graceMinutes int32) ([]Request, error)
	// Returns known locations sorted by popularity. Combines active rides/requests
	// with historical ride_stats so locations persist after rides expire.
	ListDestinations(ctx context.Context) ([]string, error)
	ListInterestsByRide(ctx context.Context, rideID pgtype.UUID) ([]Interest, error)
	// Returns all interests made by a searcher, joined with ride info for display.
	// Includes rides that may have expired (so the searcher can see their full history).
	ListInterestsBySearcher(ctx context.Context, searcherPhone string) ([]ListInterestsBySearcherRow, error)
	// Returns pending notifications for a searcher (for UI display).
	ListNotificationsForSearcher(ctx context.Context, searcherPhone string) ([]NotificationQueue, error)
	ListRequestsByPhone(ctx context.Context, arg ListRequestsByPhoneParams) ([]Request, error)
	// grace_minutes: hides rides whose flex window ended more than N minutes ago
	ListRidesActive(ctx context.Context, graceMinutes int32) ([]Ride, error)
	ListRidesByPhone(ctx context.Context, phone string) ([]Ride, error)
	ListRidesPendingFeedback(ctx context.Context) ([]Ride, error)
	ListSubscriptionsByPhone(ctx context.Context, phone string) ([]Subscription, error)
	MarkFeedbackSent(ctx context.Context, id pgtype.UUID) error
	MarkNotificationSent(ctx context.Context, id pgtype.UUID) error
	MarkNotificationSentByRideAndRequest(ctx context.Context, arg MarkNotificationSentByRideAndRequestParams) error
	SearchRides(ctx context.Context, arg SearchRidesParams) ([]Ride, error)
	SearchRidesByDate(ctx context.Context, arg SearchRidesByDateParams) ([]Ride, error)
	// Returns rides on the given date whose departure window (±flexibility) overlaps
	// the search time ± search_tolerance_minutes. Hides expired/past-grace rides.
	SearchRidesByDateTime(ctx context.Context, arg SearchRidesByDateTimeParams) ([]Ride, error)
	// Time-only search: any date, departure window overlaps search_time ± tolerance.
	SearchRidesByTime(ctx context.Context, arg SearchRidesByTimeParams) ([]Ride, error)
	// Trigram fuzzy fallback for typos/spelling variants. The `%` operator uses the
	// GIN indexes and respects pg_trgm.similarity_threshold (default 0.3). Used only
	// as a search fallback when the exact lookup returns nothing — NEVER for the
	// notification matching path, where a loose match would ping the wrong driver.
	SearchRidesFuzzy(ctx context.Context, arg SearchRidesFuzzyParams) ([]Ride, error)
	SetRideFeedbackGiven(ctx context.Context, id pgtype.UUID) error
	// ON CONFLICT (phone, endpoint) allows multiple devices per phone.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
