// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRequests = `-- name: DeleteExpiredRequests :exec
DELETE FROM requests WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRequests)
	return err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const findRequestsMatchingRide = `-- name: FindRequestsMatchingRide :many
SELECT id, searcher_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at
FROM requests
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND expires_at > NOW()
  AND (
    (date IS NULL AND departure_at IS NULL)
    OR (date IS NULL AND departure_at IS NOT NULL
        AND (departure_at::time - (flexibility * interval '1 minute')) <= ($4::timestamptz::time + ($5::int * interval '1 minute'))
        AND (departure_at::time + (flexibility * interval '1 minute')) >= ($4::timestamptz::time - ($5::int * interval '1 minute')))
    OR (date = $3 AND departure_at IS NULL)
    OR (date = $3
        AND (departure_at - (flexibility * interval '1 minute')) <= ($4::timestamptz + ($5::int * interval '1 minute'))
        AND (departure_at + (flexibility * interval '1 minute')) >= ($4::timestamptz - ($5::int * interval '1 minute')))
  )
`

type FindRequestsMatchingRideParams struct {
	Lower   string             `db:"lower"`
	Lower_2 string             `db:"lower_2"`
	Date    pgtype.Date        `db:"date"`
	Column4 pgtype.Timestamptz `db:"column_4"`
	Column5 int32              `db:"column_5"`
}

// Matches all alert modes inferred from NULL state of date/departure_at:
//
//	anytime: date IS NULL AND departure_at IS NULL
//	daily:   date IS NULL AND departure_at IS NOT NULL (time-only match)
//	day:     date set, departure_at IS NULL
//	time:    both set (overlapping window)
func (q *Queries) FindRequestsMatchingRide(ctx context.Context, arg FindRequestsMatchingRideParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, findRequestsMatchingRide,
		arg.Lower,
		arg.Lower_2,
		arg.Date,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SearcherName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, searcher_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at
FROM requests WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id pgtype.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SearcherName,
		&i.Phone,
		&i.Origin,
		&i.Destination,
		&i.Date,
		&i.DepartureAt,
		&i.Flexibility,
		&i.PostedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO requests (id, searcher_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRequestParams struct {
	ID           pgtype.UUID        `db:"id"`
	SearcherName string             `db:"searcher_name"`
	Phone        string             `db:"phone"`
	Origin       string             `db:"origin"`
	Destination  string             `db:"destination"`
	Date         pgtype.Date        `db:"date"`
	DepartureAt  pgtype.Timestamptz `db:"departure_at"`
	Flexibility  int32              `db:"flexibility"`
	PostedAt     pgtype.Timestamptz `db:"posted_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.Exec(ctx, insertRequest,
		arg.ID,
		arg.SearcherName,
		arg.Phone,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.DepartureAt,
		arg.Flexibility,
		arg.PostedAt,
		arg.ExpiresAt,
	)
	return err
}

const listActiveRequests = `-- name: ListActiveRequests :many
SELECT id, searcher_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at
FROM requests
WHERE expires_at > NOW()
  -- hide a time alert once its flex window ended more than grace_minutes ago
  AND NOT (departure_at IS NOT NULL AND EXTRACT(YEAR FROM departure_at) > 1970
           AND departure_at + ((flexibility + $1::int) * interval '1 minute') <= NOW())
  -- hide a date-only alert once its day (+ grace) has fully passed
  AND NOT (date IS NOT NULL AND departure_at IS NULL
           AND date::timestamptz + interval '1 day' + ($1::int * interval '1 minute') <= NOW())
ORDER BY
  CASE
    WHEN date IS NOT NULL OR (departure_at IS NOT NULL AND EXTRACT(YEAR FROM departure_at) > 1970) THEN 0
    WHEN departure_at IS NOT NULL THEN 1
    ELSE 2
  END,
  COALESCE(departure_at, date::timestamptz + interval '1 day' - interval '1 second') ASC NULLS LAST,
  posted_at DESC
`

// Public feed of all non-expired requests, ordered so concrete demand comes
// first and the vaguest alerts sink to the bottom:
//
//	0 dated (a one-off date+time, OR a date-only "any time that day")
//	1 a daily recurring time   2 anytime
//
// Within the dated group, sort chronologically by the effective moment — a
// date-only alert sorts at the END of its day (a one-second-before-midnight
// key), so it sits below same-day date+time entries yet above any later day.
// A daily alert carries a 1970-01-01 sentinel departure_at, so any later year
// marks a concrete one-off. Newest breaks ties.
func (q *Queries) ListActiveRequests(ctx context.Context, graceMinutes int32) ([]Request, error) {
	rows, err := q.db.Query(ctx, listActiveRequests, graceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SearcherName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByPhone = `-- name: ListRequestsByPhone :many
SELECT id, searcher_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at
FROM requests
WHERE phone = $1
  AND expires_at > NOW()
  -- hide a time alert once its flex window ended more than grace_minutes ago
  AND NOT (departure_at IS NOT NULL AND EXTRACT(YEAR FROM departure_at) > 1970
           AND departure_at + ((flexibility + $2::int) * interval '1 minute') <= NOW())
  -- hide a date-only alert once its day (+ grace) has fully passed
  AND NOT (date IS NOT NULL AND departure_at IS NULL
           AND date::timestamptz + interval '1 day' + ($2::int * interval '1 minute') <= NOW())
ORDER BY COALESCE(departure_at, date, expires_at) ASC
`

type ListRequestsByPhoneParams struct {
	Phone        string `db:"phone"`
	GraceMinutes int32  `db:"grace_minutes"`
}

func (q *Queries) ListRequestsByPhone(ctx context.Context, arg ListRequestsByPhoneParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByPhone, arg.Phone, arg.GraceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SearcherName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
