// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRideFeedback = `-- name: ClaimRideFeedback :execrows
UPDATE rides SET feedback_given = true WHERE id = $1 AND feedback_given = false
`

func (q *Queries) ClaimRideFeedback(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimRideFeedback, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRides = `-- name: DeleteExpiredRides :exec
DELETE FROM rides WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRides(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRides)
	return err
}

const deleteRide = `-- name: DeleteRide :exec
DELETE FROM rides WHERE id = $1
`

func (q *Queries) DeleteRide(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRide, id)
	return err
}

const findRidesMatchingAnytimeRequest = `-- name: FindRidesMatchingAnytimeRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND expires_at > NOW()
`

type FindRidesMatchingAnytimeRequestParams struct {
	Origin      string `db:"origin"`
	Destination string `db:"destination"`
}

func (q *Queries) FindRidesMatchingAnytimeRequest(ctx context.Context, arg FindRidesMatchingAnytimeRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingAnytimeRequest, arg.Origin, arg.Destination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingDailyRequest = `-- name: FindRidesMatchingDailyRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND expires_at > NOW()
  AND (departure_at::time - (flexibility * interval '1 minute')) <= ($3::timestamptz::time + ($4::int * interval '1 minute'))
  AND (departure_at::time + (flexibility * interval '1 minute')) >= ($3::timestamptz::time - ($4::int * interval '1 minute'))
`

type FindRidesMatchingDailyRequestParams struct {
	Origin        string             `db:"origin"`
	Destination   string             `db:"destination"`
	DepartureAt   pgtype.Timestamptz `db:"departure_at"`
	WindowMinutes int32              `db:"window_minutes"`
}

func (q *Queries) FindRidesMatchingDailyRequest(ctx context.Context, arg FindRidesMatchingDailyRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingDailyRequest,
		arg.Origin,
		arg.Destination,
		arg.DepartureAt,
		arg.WindowMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingDayRequest = `-- name: FindRidesMatchingDayRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND date = $3
  AND expires_at > NOW()
`

type FindRidesMatchingDayRequestParams struct {
	Origin      string      `db:"origin"`
	Destination string      `db:"destination"`
	Date        pgtype.Date `db:"date"`
}

func (q *Queries) FindRidesMatchingDayRequest(ctx context.Context, arg FindRidesMatchingDayRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingDayRequest, arg.Origin, arg.Destination, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingTimeRequest = `-- name: FindRidesMatchingTimeRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND date = $3
  AND expires_at > NOW()
  AND (departure_at - (flexibility * interval '1 minute')) <= ($4::timestamptz + ($5::int * interval '1 minute'))
  AND (departure_at + (flexibility * interval '1 minute')) >= ($4::timestamptz - ($5::int * interval '1 minute'))
`

type FindRidesMatchingTimeRequestParams struct {
	Origin        string             `db:"origin"`
	Destination   string             `db:"destination"`
	Date          pgtype.Date        `db:"date"`
	DepartureAt   pgtype.Timestamptz `db:"departure_at"`
	WindowMinutes int32              `db:"window_minutes"`
}

func (q *Queries) FindRidesMatchingTimeRequest(ctx context.Context, arg FindRidesMatchingTimeRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingTimeRequest,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.DepartureAt,
		arg.WindowMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideByID = `-- name: GetRideByID :one
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides WHERE id = $1
`

func (q *Queries) GetRideByID(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.DriverName,
		&i.Phone,
		&i.Origin,
		&i.Destination,
		&i.Date,
		&i.DepartureAt,
		&i.Flexibility,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.FeedbackGiven,
		&i.OriginNorm,
		&i.DestinationNorm,
		&i.DriverNameNorm,
	)
	return i, err
}

const insertRide = `-- name: InsertRide :one
INSERT INTO rides (id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (phone, driver_name_norm, origin_norm, destination_norm, departure_at) DO NOTHING
RETURNING id
`

type InsertRideParams struct {
	ID          pgtype.UUID        `db:"id"`
	DriverName  string             `db:"driver_name"`
	Phone       string             `db:"phone"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	Date        pgtype.Date        `db:"date"`
	DepartureAt pgtype.Timestamptz `db:"departure_at"`
	Flexibility int32              `db:"flexibility"`
	PostedAt    pgtype.Timestamptz `db:"posted_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at"`
}

// Idempotent insert. ON CONFLICT on the dedup key (phone + normalized driver
// name + normalized route + exact departure instant) means a re-posted ride
// inserts nothing and returns zero rows; the caller then re-reads the existing
// ride via GetRideByDedupKey.
func (q *Queries) InsertRide(ctx context.Context, arg InsertRideParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRide,
		arg.ID,
		arg.DriverName,
		arg.Phone,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.DepartureAt,
		arg.Flexibility,
		arg.PostedAt,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listRidesActive = `-- name: ListRidesActive :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($1::int * interval '1 minute') > NOW()
ORDER BY departure_at ASC
`

// grace_minutes: hides rides whose flex window ended more than N minutes ago
func (q *Queries) ListRidesActive(ctx context.Context, graceMinutes int32) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesActive, graceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesByPhone = `-- name: ListRidesByPhone :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides WHERE phone = $1 AND expires_at > NOW()
ORDER BY departure_at ASC
`

func (q *Queries) ListRidesByPhone(ctx context.Context, phone string) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesByPhone, phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRides = `-- name: SearchRides :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($3::int * interval '1 minute') > NOW()
ORDER BY departure_at ASC
`

type SearchRidesParams struct {
	Origin       string `db:"origin"`
	Destination  string `db:"destination"`
	GraceMinutes int32  `db:"grace_minutes"`
}

func (q *Queries) SearchRides(ctx context.Context, arg SearchRidesParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRides, arg.Origin, arg.Destination, arg.GraceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRidesByDate = `-- name: SearchRidesByDate :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND date = $3
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($4::int * interval '1 minute') > NOW()
ORDER BY departure_at ASC
`

type SearchRidesByDateParams struct {
	Origin       string      `db:"origin"`
	Destination  string      `db:"destination"`
	Date         pgtype.Date `db:"date"`
	GraceMinutes int32       `db:"grace_minutes"`
}

func (q *Queries) SearchRidesByDate(ctx context.Context, arg SearchRidesByDateParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRidesByDate,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.GraceMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRidesByDateTime = `-- name: SearchRidesByDateTime :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND date = $3
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($4::int * interval '1 minute') > NOW()
  AND (departure_at - (flexibility * interval '1 minute')) <= ($5::timestamptz + ($6::int * interval '1 minute'))
  AND (departure_at + (flexibility * interval '1 minute')) >= ($5::timestamptz - ($6::int * interval '1 minute'))
ORDER BY departure_at ASC
`

type SearchRidesByDateTimeParams struct {
	Origin                 string             `db:"origin"`
	Destination            string             `db:"destination"`
	Date                   pgtype.Date        `db:"date"`
	GraceMinutes           int32              `db:"grace_minutes"`
	SearchTime             pgtype.Timestamptz `db:"search_time"`
	SearchToleranceMinutes int32              `db:"search_tolerance_minutes"`
}

// Returns rides on the given date whose departure window (±flexibility) overlaps
// the search time ± search_tolerance_minutes. Hides expired/past-grace rides.
func (q *Queries) SearchRidesByDateTime(ctx context.Context, arg SearchRidesByDateTimeParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRidesByDateTime,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.GraceMinutes,
		arg.SearchTime,
		arg.SearchToleranceMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRidesByTime = `-- name: SearchRidesByTime :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm = route_norm($1::text) AND destination_norm = route_norm($2::text)
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($3::int * interval '1 minute') > NOW()
  AND (departure_at::time - (flexibility * interval '1 minute')) <= ($4::timestamptz::time + ($5::int * interval '1 minute'))
  AND (departure_at::time + (flexibility * interval '1 minute')) >= ($4::timestamptz::time - ($5::int * interval '1 minute'))
ORDER BY departure_at ASC
`

type SearchRidesByTimeParams struct {
	Origin                 string             `db:"origin"`
	Destination            string             `db:"destination"`
	GraceMinutes           int32              `db:"grace_minutes"`
	SearchTime             pgtype.Timestamptz `db:"search_time"`
	SearchToleranceMinutes int32              `db:"search_tolerance_minutes"`
}

// Time-only search: any date, departure window overlaps search_time ± tolerance.
func (q *Queries) SearchRidesByTime(ctx context.Context, arg SearchRidesByTimeParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRidesByTime,
		arg.Origin,
		arg.Destination,
		arg.GraceMinutes,
		arg.SearchTime,
		arg.SearchToleranceMinutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRidesFuzzy = `-- name: SearchRidesFuzzy :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
FROM rides
WHERE origin_norm % route_norm($1::text)
  AND destination_norm % route_norm($2::text)
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($3::int * interval '1 minute') > NOW()
ORDER BY similarity(origin_norm, route_norm($1::text))
       + similarity(destination_norm, route_norm($2::text)) DESC,
         departure_at ASC
`

type SearchRidesFuzzyParams struct {
	Origin       string `db:"origin"`
	Destination  string `db:"destination"`
	GraceMinutes int32  `db:"grace_minutes"`
}

// Trigram fuzzy fallback for typos/spelling variants. The `%` operator uses the
// GIN indexes and respects pg_trgm.similarity_threshold (default 0.3). Used only
// as a search fallback when the exact lookup returns nothing — NEVER for the
// notification matching path, where a loose match would ping the wrong driver.
func (q *Queries) SearchRidesFuzzy(ctx context.Context, arg SearchRidesFuzzyParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRidesFuzzy, arg.Origin, arg.Destination, arg.GraceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
			&i.OriginNorm,
			&i.DestinationNorm,
			&i.DriverNameNorm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRideByDedupKey = `-- name: UpdateRideByDedupKey :one
UPDATE rides SET
  driver_name = $1,
  origin      = $2,
  destination = $3,
  flexibility = $4
WHERE phone = $5
  AND driver_name_norm = route_norm($1::text)
  AND origin_norm = route_norm($2::text)
  AND destination_norm = route_norm($3::text)
  AND departure_at = $6
RETURNING id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given, origin_norm, destination_norm, driver_name_norm
`

type UpdateRideByDedupKeyParams struct {
	DriverName  string             `db:"driver_name"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	Flexibility int32              `db:"flexibility"`
	Phone       string             `db:"phone"`
	DepartureAt pgtype.Timestamptz `db:"departure_at"`
}

// Upsert tail for an idempotent re-post: when InsertRide hits the dedup-key
// conflict, refresh the mutable non-key fields and return the canonical row.
// id, phone, departure_at, posted_at and feedback_given are deliberately kept;
// the generated *_norm columns recompute from the new raw values (to the same
// key, since the key matched). Matches the uq_rides_dedup index from migration 014.
func (q *Queries) UpdateRideByDedupKey(ctx context.Context, arg UpdateRideByDedupKeyParams) (Ride, error) {
	row := q.db.QueryRow(ctx, updateRideByDedupKey,
		arg.DriverName,
		arg.Origin,
		arg.Destination,
		arg.Flexibility,
		arg.Phone,
		arg.DepartureAt,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.DriverName,
		&i.Phone,
		&i.Origin,
		&i.Destination,
		&i.Date,
		&i.DepartureAt,
		&i.Flexibility,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.FeedbackGiven,
		&i.OriginNorm,
		&i.DestinationNorm,
		&i.DriverNameNorm,
	)
	return i, err
}
