// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRides = `-- name: DeleteExpiredRides :exec
DELETE FROM rides WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRides(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRides)
	return err
}

const deleteRide = `-- name: DeleteRide :exec
DELETE FROM rides WHERE id = $1
`

func (q *Queries) DeleteRide(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRide, id)
	return err
}

const findRidesMatchingAnytimeRequest = `-- name: FindRidesMatchingAnytimeRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND expires_at > NOW()
`

type FindRidesMatchingAnytimeRequestParams struct {
	Lower   string `db:"lower"`
	Lower_2 string `db:"lower_2"`
}

func (q *Queries) FindRidesMatchingAnytimeRequest(ctx context.Context, arg FindRidesMatchingAnytimeRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingAnytimeRequest, arg.Lower, arg.Lower_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingDailyRequest = `-- name: FindRidesMatchingDailyRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND expires_at > NOW()
  AND (departure_at::time - (flexibility * interval '1 minute')) <= ($3::timestamptz::time + ($4::int * interval '1 minute'))
  AND (departure_at::time + (flexibility * interval '1 minute')) >= ($3::timestamptz::time - ($4::int * interval '1 minute'))
`

type FindRidesMatchingDailyRequestParams struct {
	Lower   string             `db:"lower"`
	Lower_2 string             `db:"lower_2"`
	Column3 pgtype.Timestamptz `db:"column_3"`
	Column4 int32              `db:"column_4"`
}

func (q *Queries) FindRidesMatchingDailyRequest(ctx context.Context, arg FindRidesMatchingDailyRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingDailyRequest,
		arg.Lower,
		arg.Lower_2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingDayRequest = `-- name: FindRidesMatchingDayRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND date = $3
  AND expires_at > NOW()
`

type FindRidesMatchingDayRequestParams struct {
	Lower   string      `db:"lower"`
	Lower_2 string      `db:"lower_2"`
	Date    pgtype.Date `db:"date"`
}

func (q *Queries) FindRidesMatchingDayRequest(ctx context.Context, arg FindRidesMatchingDayRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingDayRequest, arg.Lower, arg.Lower_2, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRidesMatchingTimeRequest = `-- name: FindRidesMatchingTimeRequest :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND date = $3
  AND expires_at > NOW()
  AND (departure_at - (flexibility * interval '1 minute')) <= ($4::timestamptz + ($5::int * interval '1 minute'))
  AND (departure_at + (flexibility * interval '1 minute')) >= ($4::timestamptz - ($5::int * interval '1 minute'))
`

type FindRidesMatchingTimeRequestParams struct {
	Lower   string             `db:"lower"`
	Lower_2 string             `db:"lower_2"`
	Date    pgtype.Date        `db:"date"`
	Column4 pgtype.Timestamptz `db:"column_4"`
	Column5 int32              `db:"column_5"`
}

func (q *Queries) FindRidesMatchingTimeRequest(ctx context.Context, arg FindRidesMatchingTimeRequestParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, findRidesMatchingTimeRequest,
		arg.Lower,
		arg.Lower_2,
		arg.Date,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideByID = `-- name: GetRideByID :one
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides WHERE id = $1
`

func (q *Queries) GetRideByID(ctx context.Context, id pgtype.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.DriverName,
		&i.Phone,
		&i.Origin,
		&i.Destination,
		&i.Date,
		&i.DepartureAt,
		&i.Flexibility,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.FeedbackGiven,
	)
	return i, err
}

const insertRide = `-- name: InsertRide :exec
INSERT INTO rides (id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRideParams struct {
	ID          pgtype.UUID        `db:"id"`
	DriverName  string             `db:"driver_name"`
	Phone       string             `db:"phone"`
	Origin      string             `db:"origin"`
	Destination string             `db:"destination"`
	Date        pgtype.Date        `db:"date"`
	DepartureAt pgtype.Timestamptz `db:"departure_at"`
	Flexibility int32              `db:"flexibility"`
	PostedAt    pgtype.Timestamptz `db:"posted_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) InsertRide(ctx context.Context, arg InsertRideParams) error {
	_, err := q.db.Exec(ctx, insertRide,
		arg.ID,
		arg.DriverName,
		arg.Phone,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.DepartureAt,
		arg.Flexibility,
		arg.PostedAt,
		arg.ExpiresAt,
	)
	return err
}

const listRidesActive = `-- name: ListRidesActive :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($1::int * interval '1 minute') > NOW()
ORDER BY departure_at ASC
`

// grace_minutes: hides rides whose flex window ended more than N minutes ago
func (q *Queries) ListRidesActive(ctx context.Context, graceMinutes int32) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesActive, graceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesByPhone = `-- name: ListRidesByPhone :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides WHERE phone = $1 AND expires_at > NOW()
ORDER BY departure_at ASC
`

func (q *Queries) ListRidesByPhone(ctx context.Context, phone string) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesByPhone, phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesPendingFeedback = `-- name: ListRidesPendingFeedback :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE departure_at BETWEEN (NOW() - INTERVAL '23 hours') AND (NOW() - INTERVAL '30 minutes')
  AND feedback_given = false
  AND expires_at > NOW()
ORDER BY departure_at ASC
`

func (q *Queries) ListRidesPendingFeedback(ctx context.Context) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesPendingFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRides = `-- name: SearchRides :many
SELECT id, driver_name, phone, origin, destination, date, departure_at, flexibility, posted_at, expires_at, feedback_given
FROM rides
WHERE LOWER(origin) = LOWER($1) AND LOWER(destination) = LOWER($2)
  AND expires_at > NOW()
  AND departure_at + (flexibility * interval '1 minute') + ($3::int * interval '1 minute') > NOW()
ORDER BY departure_at ASC
`

type SearchRidesParams struct {
	Lower        string `db:"lower"`
	Lower_2      string `db:"lower_2"`
	GraceMinutes int32  `db:"grace_minutes"`
}

func (q *Queries) SearchRides(ctx context.Context, arg SearchRidesParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, searchRides, arg.Lower, arg.Lower_2, arg.GraceMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ride{}
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.DriverName,
			&i.Phone,
			&i.Origin,
			&i.Destination,
			&i.Date,
			&i.DepartureAt,
			&i.Flexibility,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.FeedbackGiven,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRideFeedbackGiven = `-- name: SetRideFeedbackGiven :exec
UPDATE rides SET feedback_given = true WHERE id = $1
`

func (q *Queries) SetRideFeedbackGiven(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setRideFeedbackGiven, id)
	return err
}
