// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package queries

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertSettingIfAbsent = `-- name: InsertSettingIfAbsent :exec
INSERT INTO app_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type InsertSettingIfAbsentParams struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

func (q *Queries) InsertSettingIfAbsent(ctx context.Context, arg InsertSettingIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertSettingIfAbsent, arg.Key, arg.Value)
	return err
}
