// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRideEventCounts = `-- name: GetRideEventCounts :one
SELECT
  COUNT(*)                                                                           AS all_time,
  COUNT(*) FILTER (WHERE posted_at >= DATE_TRUNC('year',  NOW()))                   AS this_year,
  COUNT(*) FILTER (WHERE posted_at >= DATE_TRUNC('month', NOW()))                   AS this_month
FROM ride_events
`

type GetRideEventCountsRow struct {
	AllTime   int64 `db:"all_time"`
	ThisYear  int64 `db:"this_year"`
	ThisMonth int64 `db:"this_month"`
}

func (q *Queries) GetRideEventCounts(ctx context.Context) (GetRideEventCountsRow, error) {
	row := q.db.QueryRow(ctx, getRideEventCounts)
	var i GetRideEventCountsRow
	err := row.Scan(&i.AllTime, &i.ThisYear, &i.ThisMonth)
	return i, err
}

const getRideStatsTotals = `-- name: GetRideStatsTotals :one
SELECT
  COUNT(*) FILTER (WHERE taken = true)                                                     AS total_confirmed,
  COUNT(*) FILTER (WHERE taken = true AND recorded_at >= DATE_TRUNC('week', NOW()))        AS total_this_week
FROM ride_stats
`

type GetRideStatsTotalsRow struct {
	TotalConfirmed int64 `db:"total_confirmed"`
	TotalThisWeek  int64 `db:"total_this_week"`
}

func (q *Queries) GetRideStatsTotals(ctx context.Context) (GetRideStatsTotalsRow, error) {
	row := q.db.QueryRow(ctx, getRideStatsTotals)
	var i GetRideStatsTotalsRow
	err := row.Scan(&i.TotalConfirmed, &i.TotalThisWeek)
	return i, err
}

const getSearchEventCounts = `-- name: GetSearchEventCounts :one
SELECT
  COUNT(*)                                                                           AS all_time,
  COUNT(*) FILTER (WHERE searched_at >= DATE_TRUNC('year',  NOW()))                 AS this_year,
  COUNT(*) FILTER (WHERE searched_at >= DATE_TRUNC('month', NOW()))                 AS this_month
FROM search_events
`

type GetSearchEventCountsRow struct {
	AllTime   int64 `db:"all_time"`
	ThisYear  int64 `db:"this_year"`
	ThisMonth int64 `db:"this_month"`
}

func (q *Queries) GetSearchEventCounts(ctx context.Context) (GetSearchEventCountsRow, error) {
	row := q.db.QueryRow(ctx, getSearchEventCounts)
	var i GetSearchEventCountsRow
	err := row.Scan(&i.AllTime, &i.ThisYear, &i.ThisMonth)
	return i, err
}

const getTopRoutes = `-- name: GetTopRoutes :many
SELECT origin, destination, COUNT(*) AS count
FROM ride_stats
WHERE taken = true
  AND recorded_at >= DATE_TRUNC('week', NOW())
GROUP BY origin, destination
ORDER BY count DESC
LIMIT 5
`

type GetTopRoutesRow struct {
	Origin      string `db:"origin"`
	Destination string `db:"destination"`
	Count       int64  `db:"count"`
}

func (q *Queries) GetTopRoutes(ctx context.Context) ([]GetTopRoutesRow, error) {
	rows, err := q.db.Query(ctx, getTopRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopRoutesRow{}
	for rows.Next() {
		var i GetTopRoutesRow
		if err := rows.Scan(&i.Origin, &i.Destination, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRideEvent = `-- name: InsertRideEvent :exec
INSERT INTO ride_events (origin, destination) VALUES ($1, $2)
`

type InsertRideEventParams struct {
	Origin      string `db:"origin"`
	Destination string `db:"destination"`
}

func (q *Queries) InsertRideEvent(ctx context.Context, arg InsertRideEventParams) error {
	_, err := q.db.Exec(ctx, insertRideEvent, arg.Origin, arg.Destination)
	return err
}

const insertRideStat = `-- name: InsertRideStat :exec
INSERT INTO ride_stats (origin, destination, ride_date, taken) VALUES ($1, $2, $3, $4)
`

type InsertRideStatParams struct {
	Origin      string      `db:"origin"`
	Destination string      `db:"destination"`
	RideDate    pgtype.Date `db:"ride_date"`
	Taken       bool        `db:"taken"`
}

func (q *Queries) InsertRideStat(ctx context.Context, arg InsertRideStatParams) error {
	_, err := q.db.Exec(ctx, insertRideStat,
		arg.Origin,
		arg.Destination,
		arg.RideDate,
		arg.Taken,
	)
	return err
}

const insertSearchEvent = `-- name: InsertSearchEvent :exec
INSERT INTO search_events (origin, destination) VALUES ($1, $2)
`

type InsertSearchEventParams struct {
	Origin      string `db:"origin"`
	Destination string `db:"destination"`
}

func (q *Queries) InsertSearchEvent(ctx context.Context, arg InsertSearchEventParams) error {
	_, err := q.db.Exec(ctx, insertSearchEvent, arg.Origin, arg.Destination)
	return err
}
