// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package queries

import (
	"context"
)

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE phone = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, deleteSubscription, phone)
	return err
}

const getSubscriptionByPhone = `-- name: GetSubscriptionByPhone :one
SELECT id, phone, endpoint, p256dh, auth
FROM subscriptions WHERE phone = $1
`

func (q *Queries) GetSubscriptionByPhone(ctx context.Context, phone string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPhone, phone)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (id, phone, endpoint, p256dh, auth)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (phone) DO UPDATE SET endpoint = $2, p256dh = $3, auth = $4
`

type UpsertSubscriptionParams struct {
	Phone    string `db:"phone"`
	Endpoint string `db:"endpoint"`
	P256dh   string `db:"p256dh"`
	Auth     string `db:"auth"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.Phone,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
